#!/bin/bash
#SBATCH --qos medium
#SBATCH --account iacc_gbuzzell
#SBATCH --partition 6g-per-core


#SBATCH --nodes=1                # node count
#SBATCH --ntasks=1               # total number of tasks across all nodes
#SBATCH --time=00:24:00          # total run time limit (HH:MM:SS)

# load singularity module
module load singularity-3.5.3

# use singularity image to run all tests
singularity exec --bind /home/data/NDClab/data/base-eeg/CMI container/run-container.simg pytest
