name: Pytest on docker
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  container-test:
    runs-on: ubuntu-latest
    steps:
      - name: Get docker container
        run: docker pull ndclab/pepper_container:szegedi-1.0.0
      - name: Verify docker containers
        run: docker run --name pepper -w /projects/pepper-pipeline ndclab/pepper_container:szegedi-1.0.0
      - name: Run pytest in docker 
        run: docker exec ndclab/pepper_container:szegedi-1.0.0 conda run -n pipe pytest scripts/tests/