name: Pytest
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    container: ndclab/pepper_container:szegedi-1.0.0
    steps:
      - name: Activate pipe and run pytest
        run: conda activate pipe 
        run: sudo pytest 