name: Pytest on docker
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  container-test:
    runs-on: ubuntu-latest
    container: ndclab/pepper_container:szegedi-1.0.0
    steps:
      - name: Clone in data into container
        run: git clone https://github.com/NDCLab/pepper-pipeline.git && cd pepper-pipeline
      - name: Run pytest in conda env
        run: conda run -n pipe pytest scripts/tests/