name: Pytest on docker
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  container-test:
    runs-on: ubuntu-latest
    container: ndclab/pepper_container:szegedi-1.0.0
    steps:
      - name: List conda info on container
        run: conda info 
      - name: Initialize and restart shell
        run: conda init bash && exec bash
      - name: Activate pipe conda environment
        run: conda activate pipe
      - name: Verify pipe environment
        run: conda env list
      - name: Run pytest
        run: pytest scripts/tests/